from yacs.config import CfgNode as CN

_C = CN()
_C.DATASET = CN()
_C.TRAIN = CN()
_C.MODEL = CN()
_C.MODEL.SDF_NETWORK= CN()
_C.MODEL.NERF=CN()
_C.MODEL.VARIANCE_NETWORK=CN()
_C.MODEL.RENDERING_NETWORK=CN()




_C.EXP_NAME = "Neus"



# Dataset Parameters
_C.DATASET.DATA_DIR="/media/zliu/36f46db9-1b91-44e8-bd8a-67578586dec9/dataset/DTU/dtu_scan24/"
_C.DATASET.RENDERED_CAMERAS_NAME="cameras_sphere.npz"
_C.DATASET.OBJECTS_CAMERAS_NAME="cameras_sphere.npz"


# Train Parameters
_C.TRAIN.LEARNING_RATE=5e-4
_C.TRAIN.LEARNING_ALPHA=0.05
_C.TRAIN.END_ITERATIONS=300000

_C.TRAIN.BATCH_SIZE=512
_C.VALIDATE_RESOLUTATION_LEVEL=4
_C.TRAIN.WARM_UP_END=5000
_C.TRAIN.ANNEAL_END=50000
_C.TRAIN.USE_WHITE_BKGD=False

_C.TRAIN.SAVE_FREQ=1000
_C.TRAIN.VAL_FREQ=2500
_C.TRAIN.VAL_MESH_FREQ=5000
_C.TRAIN.REPORT_FREQ=100

_C.TRAIN.IGR_WEIGHT=0.1
# Essential for using instance mask for supervision or not.
_C.TRAIN.MASK_WEIGHT=0.0


# Models Parameters
_C.MODEL.SDF_NETWORK.D_OUT = 257
_C.MODEL.SDF_NETWORK.D_IN=3
_C.MODEL.SDF_NETWORK.D_HIDDEN=256
_C.MODEL.SDF_NETWORK.N_LAYERS=8
_C.MODEL.SDF_NETWORK.SKIP_IN=[4]
_C.MODEL.SDF_NETWORK.MULTIRES=6
_C.MODEL.SDF_NETWORK.BIAS=0.5
_C.MODEL.SDF_NETWORK.SCALE=1.0
_C.MODEL.SDF_NETWORK.GEOMETRIC_INIT=True
_C.MODEL.SDF_NETWORK.WEIGHT_NORM=True



